apps/crud/models.py
from datetime import datetime

from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

#db.Modelに加えてUserMixinを継承したUserクラスを作成
class User(db.Model, UserMixin):
    #テーブル名を指定
    __tablename__ = "users"

    #カラムを定義
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    #パスワードをセットするためのプロパティ
    @property
    def password(self):
        raise AttributeError("読み取り不可")
    
    #パスワードをセットするためのセッター関数でハッシュ化したパスワードをセット
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    #パスワードをチェックする
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    #メールアドレス重複チェックをする
    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None
    
#ログインしているユーザ情報を取得する関数
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length

#ユーザ新規作成とユーザ編集フォームクラス
class UserForm(FlaskForm):
    #ユーザフォームのusername属性のラベルとバリデータを設定する
    username = StringField(
        "ユーザ名",
        validators=[
            DataRequired(message="ユーザ名は必須です。"),
            length(max=30, message="30文字以内で入力してください。"),
        ],
    )

    #ユーザフォームemail属性のラベルとバリデータを設定する
    email = StringField(
        "メールアドレス",
        validators=[
            DataRequired(message="メールアドレスは必須です。"),
            Email(message="メールアドレスの形式で入力してください。"),
        ],
    )

    #ユーザフォームpassword属性のラベルとバリデータを設定する
    password = PasswordField(
        "パスワード",
        validators=[DataRequired(message="パスワードは必須です。")],
    )

    #ユーザフォームsubmitの文言を設定する
    submit = SubmitField("新規登録")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import UserForm
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

#Blueprintでcrudアプリ生成
crud = Blueprint(
    "crud",                         #エンドポイント前の階層名
    __name__,                       #通常は、__name__を指定する
    template_folder="templates",    #テンプレートフォルダ名
    static_folder="static",         #静的ファイルのフォルダ名
)

#indexエンドポイントを作成し、index.htmlを返す
@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html")

@crud.route("/sql")
@login_required
def sql():
    db.session.query(User).all()    #全てSELECT

    db.session.query(User).first()  #１件のみSELECT

    db.session.query(User).get(2)   #プライマリキーの値を指定してSELECT

    db.session.query(User).count()  #検索件数をSELECT

    #db.session.query(User).paginate(2, 10, False)  #2ページ目、10件ずつ

    db.session.query(User).filter_by(id=2, username="admin").all()      #filter_byでWHERE句
    db.session.query(User).filter(User.id==2, User.username=="admin")   #filterでWHERE句　※こっちの方がめんどくさそう

    db.session.query(User).limit(1).all()               #先頭の1件のみ取得
    db.session.query(User).limit(1).offset(2).all()     #3番目のレコードから1件のみ取得

    db.session.query(User).order_by("username").all()   #ユーザ名で昇順にして取得

    db.session.query(User).group_by("username").all()   #ユーザ名でグループ化

    #データの追加(INSERT)
    user = User(username="谷口幸正", email="tani@gmail.com", password="パスワード")
    db.session.add(user)    #addで追加して、
    db.session.commit()     #commitしないと変更が反映されない！！

    #データの更新(UPDATE)
    user = db.session.query(User).filter_by(id=1).first()   #検索して
    user.username = "大原　太郎"         #書き換える
    user.email = "asdfghjkl@gmail.com"  
    user.password = "パスワード２"
    db.session.add(user)                #書き換えたものを追加する
    db.session.commit()                 #コミットして完了

    #データの削除(DELETE)
    user = db.session.query(User).filter_by(id=1).delete()
    db.session.commit()

    return "コンソールログを確認してください"

@crud.route("/users/new", methods=["GET", "POST"])
@login_required
def create_user():
    #UserFormをインスタンス化
    form = UserForm()

    #フォームの値をバリデートする
    if form.validate_on_submit():
        #ユーザを作成
        user = User(
            username = form.username.data,
            email = form.email.data,
            password = form.password.data,
        )

        #ユーザを追加してコミット
        db.session.add(user)
        db.session.commit()

        #ユーザの一覧画面へリダイレクト
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)

@crud.route("/users")
@login_required
def users():
    """ユーザの一覧を取得"""
    users = User.query.all()
    return render_template("crud/index.html", users=users)

@crud.route("/users/<user_id>", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    form = UserForm()

    #Userモデルを利用してユーザを取得
    user = User.query.filter_by(id=user_id).first()

    #formからサブミットされた場合はユーザ情報を更新しユーザの一覧画面へリダイレクト
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    
    #GETの場合はHTMLを返す
    return render_template("crud/edit.html", user=user, form=form)

#ユーザ削除
@crud.route("/users/<user_id>/delete", methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- 継承先で実装 -->
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}"/>
    </head>
    <body>
        <div>
            {% if current_user.is_authenticated %}
            <p>
                <span>{{ current_user.username }}</span> :
                <span><a href="{{ url_for('auth.logout') }}">ログアウト</a></span>
            </p>
            {% endif %}
        </div>
        <!-- contentを継承先で実装する -->
        {% block content %}{% endblock %}
    </body>
</html>

apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}ユーザ新規作成{% endblock %}
{% block content %}
<h2>ユーザ新規作成</h2>
<form action="{{ url_for('crud.create_user') }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="ユーザ名") }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.email.label }} {{ form.email(placeholder="メールアドレス") }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.password.label }} {{ form.password(placeholder="パスワード") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends "crud/base.html" %}
{% block title %}ユーザ編集{% endblock %}
{% block content %}
<h2>ユーザ編集</h2>

<form action="{{ url_for('crud.edit_user', user_id=user.id) }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}

    <!-- ユーザ名 -->
    <p>
        {{ form.username.label }} {{ form.username(placeholder="ユーザ名", value=user.username) }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    
    <!-- メールアドレス -->
    <p>
        {{ form.email.label }} {{ form.email(placeholder="メールアドレス", value=user.email) }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <!-- パスワード -->
    <p>
        {{ form.password.label }} {{ form.password(placeholder="パスワード") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p><input type="submit" value="更新"/></p>
</form>

<form action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="POST">
    {{ form.csrf_token }}
    <input type="submit" value="削除">
</form>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %}ユーザの一覧{% endblock %}
{% block content %}
<h2>ユーザの一覧</h2>

<a href="{{ url_for('crud.create_user') }}">ユーザ新規作成</a>

<table>
    <tr>
        <th>ユーザID</th>
        <th>ユーザ名</th>
        <th>メールアドレス</th>
    </tr>
    {% for user in users %}
    <tr>
        <!-- aタグでリンクを追加 -->
        <td>
            <a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a>
        </td>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}